# Generated by Django 5.1 on 2025-01-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('Image', models.ImageField(upload_to='ev_station/')),
                ('address', models.TextField()),
                ('working_hours', models.CharField(default='', max_length=50)),
                ('connectors', models.JSONField()),
                ('rate_per_minute', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('capacity', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
