# Generated by Django 5.1 on 2025-01-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargingstations',
            old_name='Image',
            new_name='image',
        ),
    ]
