# Generated by Django 5.1 on 2025-01-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_chargingslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingslot',
            name='date',
        ),
    ]
