# Generated by Django 5.1 on 2025-01-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_chargingslot_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargingstations',
            old_name='rate_per_minute',
            new_name='rate_per_slot',
        ),
    ]
