# Generated by Django 5.1 on 2025-01-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('owner_name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=50)),
                ('number', models.CharField(default='', max_length=15)),
                ('address', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='station', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_center_photos/')),
                ('place', models.CharField(default='', max_length=100)),
                ('working_hours', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
