# Generated by Django 5.1 on 2025-01-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_centre',
            name='number',
        ),
        migrations.AddField(
            model_name='service_centre',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
