# Generated by Django 5.1 on 2025-01-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_remove_service_centre_number_service_centre_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_centre',
            name='place',
        ),
    ]
