# Generated by Django 5.1 on 2025-01-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_remove_service_centre_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_centre',
            name='utype',
            field=models.CharField(default='owner', max_length=10),
        ),
    ]
