# Generated by Django 5.1 on 2025-01-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_service_centre_utype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_centre',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='service_centre',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='service_centre',
            name='working_hours',
            field=models.CharField(default='', max_length=55),
        ),
    ]
