# Generated by Django 5.1 on 2025-01-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0008_alter_repair_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_centre',
            name='location',
        ),
        migrations.AddField(
            model_name='service_centre',
            name='latitutde',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='service_centre',
            name='longitutde',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='service_centre',
            name='utype',
            field=models.CharField(default='service_center', max_length=10),
        ),
    ]
