# Generated by Django 5.1 on 2025-01-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0010_rename_latitutde_service_centre_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_centre',
            old_name='longitutde',
            new_name='longitude',
        ),
    ]
