# Generated by Django 5.1 on 2025-01-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0014_alter_service_centre_utype'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_centre',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='service_centre',
            name='utype',
            field=models.CharField(default='service_centre', max_length=20),
        ),
    ]
