# Generated by Django 5.1 on 2025-01-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0015_service_centre_status_alter_service_centre_utype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
