# Generated by Django 5.1 on 2025-01-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0016_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='service_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_app.service_centre'),
        ),
    ]
