# Generated by Django 5.1 on 2025-01-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0018_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
