# Generated by Django 5.1 on 2025-01-28 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0020_delete_repair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(default='', max_length=50)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_app.employee')),
                ('service_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_app.service_centre')),
            ],
        ),
    ]
