# Generated by Django 5.1 on 2025-01-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0022_alter_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
