# Generated by Django 5.1 on 2025-01-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0024_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
