# Generated by Django 5.1 on 2025-01-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0025_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
